apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: srelab
servers: 1
agents: 2
kubeAPI:
  hostPort: "6443"
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
k3s:
  extraArgs:
    - arg: "--disable=traefik@server"
      nodeFilters:
        - server: 0
